version: '3.8'
services:
  web:
    container_name: flask-app
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_ENV=development
    command: python app.py
